[package]
name = "ytdlp-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
url = { workspace = true }
regex = { workspace = true }
ureq = { version = "2", default-features = false, features = ["native-tls"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
